name: Upload to PyPI

on:
  release:
    types: [created]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python3.9 -m pip install "flit~=3.0"
    - name: Build and publish
      env:
        FLIT_USERNAME: ${{ secrets.PYPI_USERNAME }}
        FLIT_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        flit install
        flit publish
